# -*- coding: utf-8 -*-
"""
Veersa – Follow-Up Scheduler Module

Manages scheduled follow-up actions generated by the planner.
Stores items in a local JSON file for persistence across sessions.

Designed to be easily extended to APScheduler, Celery, or cron.

Usage:
    from scheduler import create_schedule, list_schedules, cancel_schedule
    item = create_schedule(plan, duration_days=3)
    all_items = list_schedules()
    cancel_schedule(item["id"])
"""

import json
import os
import uuid
from datetime import datetime, timedelta


# ─────────────────────────────────────────────────────────────
# Storage Configuration
# ─────────────────────────────────────────────────────────────

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
_SCHEDULE_FILE = os.path.join(_DATA_DIR, "schedules.json")


def _load_schedules() -> list:
    """Load all scheduled items from disk."""
    if not os.path.exists(_SCHEDULE_FILE):
        return []
    try:
        with open(_SCHEDULE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return []


def _save_schedules(schedules: list) -> None:
    """Persist scheduled items to disk."""
    os.makedirs(_DATA_DIR, exist_ok=True)
    with open(_SCHEDULE_FILE, "w", encoding="utf-8") as f:
        json.dump(schedules, f, indent=2, ensure_ascii=False)


# ─────────────────────────────────────────────────────────────
# Follow-Up Timing Logic
# ─────────────────────────────────────────────────────────────

# Default follow-up delays (in days) based on plan priority
_FOLLOWUP_DELAYS = {
    "URGENT": 1,       # next day
    "MODERATE": 3,     # within 3 days
    "ROUTINE": 7,      # within a week
}


def _compute_followup_date(
    priority: str,
    duration_days: int,
) -> str:
    """
    Compute the recommended follow-up date.

    For urgent cases, the follow-up is the next day regardless.
    For moderate/routine, the delay scales slightly with symptom
    duration to account for chronic vs. acute presentations.

    Returns an ISO-format date string.
    """
    base_delay = _FOLLOWUP_DELAYS.get(priority.upper(), 7)

    # For longer-duration symptoms, pull follow-up slightly earlier
    if duration_days >= 7 and priority != "URGENT":
        base_delay = max(1, base_delay - 1)

    followup_dt = datetime.now() + timedelta(days=base_delay)
    return followup_dt.strftime("%Y-%m-%d")


# ─────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────

def create_schedule(plan: dict, duration_days: int = 1) -> dict:
    """
    Create a new scheduled follow-up from a planner output.

    Parameters
    ----------
    plan : dict
        The plan dictionary from ``generate_plan()``.
    duration_days : int
        The symptom duration reported by the patient (used to
        fine-tune follow-up timing).

    Returns
    -------
    dict
        The created schedule item with fields:
        id, title, priority, specialist, scheduled_date,
        status, created_at, actions.
    """
    priority = plan.get("priority", "ROUTINE")
    specialist = plan.get("based_on", {}).get("specialist", "General Physician")
    followup_date = _compute_followup_date(priority, duration_days)

    item = {
        "id": str(uuid.uuid4())[:8],
        "title": plan.get("title", "Follow-Up Appointment"),
        "priority": priority,
        "specialist": specialist,
        "scheduled_date": followup_date,
        "status": "SCHEDULED",
        "created_at": datetime.now().isoformat(),
        "actions": plan.get("recommended_actions", []),
    }

    schedules = _load_schedules()
    schedules.append(item)
    _save_schedules(schedules)

    return item


def list_schedules() -> list:
    """
    Return all scheduled follow-up items.

    Returns
    -------
    list[dict]
        Each dict has: id, title, priority, specialist,
        scheduled_date, status, created_at, actions.
    """
    return _load_schedules()


def cancel_schedule(schedule_id: str) -> bool:
    """
    Cancel (mark as CANCELLED) a scheduled follow-up by its ID.

    Parameters
    ----------
    schedule_id : str
        The 8-character ID of the schedule item to cancel.

    Returns
    -------
    bool
        True if the item was found and cancelled, False otherwise.
    """
    schedules = _load_schedules()
    found = False
    for item in schedules:
        if item["id"] == schedule_id:
            item["status"] = "CANCELLED"
            found = True
            break
    if found:
        _save_schedules(schedules)
    return found


def complete_schedule(schedule_id: str) -> bool:
    """
    Mark a scheduled follow-up as COMPLETED.

    Parameters
    ----------
    schedule_id : str
        The 8-character ID of the schedule item.

    Returns
    -------
    bool
        True if found and updated, False otherwise.
    """
    schedules = _load_schedules()
    found = False
    for item in schedules:
        if item["id"] == schedule_id:
            item["status"] = "COMPLETED"
            found = True
            break
    if found:
        _save_schedules(schedules)
    return found


def clear_all_schedules() -> int:
    """
    Remove all scheduled items. Returns the count of removed items.
    """
    schedules = _load_schedules()
    count = len(schedules)
    _save_schedules([])
    return count
